-- 일반사용자 권한 설정 --
CREATE USER IF NOT EXISTS 'zeroskill2400'@'%' IDENTIFIED WITH 'caching_sha2_password' BY 'Zeroskill2400';
GRANT ALL PRIVILEGES ON *.* TO 'zeroskill2400'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS db;

use db;

CREATE TABLE IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    phone VARCHAR(255) NOT NULL,
    gender ENUM('MALE', 'FEMALE', 'ANONYMOUS') NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    deleted_by INT DEFAULT NULL
);


FLUSH PRIVILEGES;